using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class charactermovement : MonoBehaviour
{
    public float moveSpeed = 10f; // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½x
    public float jumpForce = 5f; // ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½
    private Rigidbody rb;
    private Camera mainCamera;
    private bool isGrounded;
    private Animator animator; // ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½^ï¿½[
    Vector3 position; // ï¿½ï¿½ï¿½Ì‚ÌˆÊ’uï¿½ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½

    public float rotationSpeed = 100f; // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½]ï¿½ï¿½ï¿½x

    void Start()
    {
        rb = GetComponent<Rigidbody>();
        mainCamera = Camera.main;
        animator = GetComponent<Animator>(); // ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½^ï¿½[ï¿½Ìæ“¾
    }

    void Update()
    {
        Move();
        RotateCamera();
        position = transform.position; // ï¿½ï¿½ï¿½İˆÊ’uï¿½Ì•Û‘ï¿½
        rb.constraints = RigidbodyConstraints.FreezeRotation;
        if (Input.GetButtonDown("Jump") && isGrounded)
        {
            Jump();
        }
    }

    void Move()
    {
        float moveHorizontal = Input.GetAxis("HorizontalWASD");
        float moveVertical = -Input.GetAxis("VerticalWASD"); // ï¿½Oï¿½ï¿½Ì“ï¿½ï¿½ï¿½ï¿½ğ”½“]

        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì‘Oï¿½ï¿½ï¿½ï¿½ï¿½Æ‰Eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½æ“¾
        Vector3 cameraForward = mainCamera.transform.forward;
        Vector3 cameraRight = mainCamera.transform.right;

        // Yï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½É‚ï¿½ï¿½ÄAXZï¿½ï¿½ï¿½Ê‚É“ï¿½ï¿½e
        cameraForward.y = 0;
        cameraRight.y = 0;

        cameraForward.Normalize();
        cameraRight.Normalize();

        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ÉŠï¿½Ã‚ï¿½ï¿½ÄˆÚ“ï¿½ï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Z
        Vector3 movement = (cameraForward * moveVertical + cameraRight * moveHorizontal) * moveSpeed * Time.deltaTime;

        rb.MovePosition(transform.position + movement);

        // ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
        bool walking = moveHorizontal != 0 || moveVertical != 0;
        animator.SetBool("isWalking", walking);
    }

    void RotateCamera()
    {
        float rotateHorizontal = Input.GetAxis("HorizontalArrow");
        float rotateVertical = Input.GetAxis("VerticalArrow");

        // ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½É‰ï¿½]
        transform.Rotate(Vector3.up, rotateHorizontal * rotationSpeed * Time.deltaTime);

        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½É”ï¿½ï¿½f
        float newPitch = rotateVertical * rotationSpeed * Time.deltaTime;
        float newRotation = mainCamera.transform.eulerAngles.x - newPitch;

        // ï¿½ã‰ºï¿½ï¿½ï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½pï¿½xï¿½ğ§Œï¿½ï¿½ï¿½ï¿½ï¿½
        if (newRotation > 180f)
        {
            newRotation -= 360f;
        }
        newRotation = Mathf.Clamp(newRotation, -30f, 30f); // ï¿½Å‘ï¿½30ï¿½xï¿½Ü‚Å‰ï¿½]ï¿½Â”\ï¿½Éï¿½ï¿½ï¿½

        mainCamera.transform.RotateAround(transform.position, mainCamera.transform.right, -newPitch);
    }

    void Jump()
    {
        rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);
        isGrounded = false;

        // ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
        animator.SetBool("isJumping", true);
    }

    void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("Ground"))
        {
            isGrounded = true;
            animator.SetBool("isJumping", false); // ï¿½ï¿½ï¿½nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        }

        Debug.Log("object =" + collision.gameObject.name);
        if (collision.transform.root.gameObject.name == "Wall") // ï¿½uï¿½ï¿½ï¿½vï¿½ÈŠOï¿½Æ‚ÌÕ“Ë‚ï¿½ï¿½ï¿½ï¿½è‚³ï¿½ê‚½
        {
            Vector3 boundVec = transform.position - position; // ï¿½Ú“ï¿½ï¿½xï¿½Nï¿½gï¿½ï¿½
            //Debug.Log("object =" + boundVec);
            transform.position = position - boundVec; // ï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½
        }
    }
}
